import { FC } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "animate.css";
import "./globals.css";
import { ChildrenType } from "./utils/types";
import AppProvider from "./AppProvider";
import SocketProvider from "./utils/context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<ChildrenType> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-neutral-900`}>
        <SocketProvider>
          <AppProvider>{children}</AppProvider>
        </SocketProvider>
      </body>
    </html>
  );
};

export default RootLayout;
